# Generated by Django 2.2.7 on 2019-11-24 02:44

import alumnos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20191122_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=254, validators=[alumnos.validators.validate_email]),
        ),
    ]
