# Generated by Django 2.2.6 on 2019-11-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0002_materia_semestre'),
        ('alumnos', '__first__'),
        ('salones', '0002_auto_20191027_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.CharField(choices=[('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-1', '12-1')], default='7-8', max_length=3)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.Salon')),
            ],
        ),
    ]
