# Generated by Django 2.2.7 on 2019-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='alumno',
        ),
        migrations.AddField(
            model_name='grupo',
            name='alumno',
            field=models.ManyToManyField(to='alumnos.Alumno'),
        ),
    ]
