# Generated by Django 2.2.7 on 2019-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20191120_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='alumno',
            field=models.ManyToManyField(related_name='alumnos', to='alumnos.Alumno'),
        ),
    ]
