# Generated by Django 2.2.7 on 2019-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0002_auto_20191027_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='nombre',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
